### ISSUE TITLE
楼主请问为何我打包完33.3M 而下载的apk才8.89M  是我打包姿势不对么？ 求教😊

### ISSUE THREAD

**Issue by GitHubAsural** [Ha2ryZhang/alltv_flutter#1]

**Comment by GitHubAsural** [comment]
新创建的应用打包也需要15M

**Comment by Ha2ryZhang** [comment]
> `新创建的应用打包也需要15M`

默认打包的话会把v8  v7 x86_64架构的包都集成在一个包里面。
`flutter build apk --split-per-abi`可以分开，一般v7的大部分手机都支持了。这样节省包体积。
